[package]
name = "wasmtime-obj"
version = "0.1.0"
authors = ["The Wasmtime Project Developers"]
description = "Native object file output for WebAsssembly code in Wasmtime"
publish = false
repository = "https://github.com/CraneStation/wasmtime"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
edition = "2018"

[dependencies]
# cranelift-codegen = { version = "0.36.0", features = ["enable-serde"] }
# cranelift-entity = { version = "0.36.0", features = ["enable-serde"] }
# cranelift-wasm = { version = "0.36.0", features = ["enable-serde"] }

# cranelift-codegen = { version = "0.36.0", features = ["enable-serde"] }
cranelift-codegen = { path = "../../cranelift/cranelift-codegen", features = ["enable-serde"] }

# cranelift-entity = { version = "0.36.0", features = ["enable-serde"] }
cranelift-entity = { path = "../../cranelift/cranelift-entity", features = ["enable-serde"] }

# cranelift-wasm = { version = "0.36.0", features = ["enable-serde"] }
cranelift-wasm = { path = "../../cranelift/cranelift-wasm", features = ["enable-serde"] }

wasmtime-environ = { path = "../wasmtime-environ" }
faerie = "0.10.1"
