[package]
name = "wasmtime-wast"
version = "0.2.0"
authors = ["The Wasmtime Project Developers"]
description = "wast testing support for wasmtime"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/CraneStation/wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
edition = "2018"

[dependencies]
<<<<<<< HEAD
# cranelift-codegen = { version = "0.36.0", features = ["enable-serde"] }
# cranelift-native = "0.36.0"
# cranelift-wasm = { version = "0.36.0", features = ["enable-serde"] }
# cranelift-entity = { version = "0.36.0", features = ["enable-serde"] }

# cranelift-codegen = { version = "0.36.0", features = ["enable-serde"] }
cranelift-codegen = { path = "../../cranelift/cranelift-codegen", features = ["enable-serde"] }

cranelift-native = { path = "../../cranelift/cranelift-native"}

# cranelift-entity = { version = "0.36.0", features = ["enable-serde"] }
cranelift-entity = { path = "../../cranelift/cranelift-entity", features = ["enable-serde"] }

# cranelift-wasm = { version = "0.36.0", features = ["enable-serde"] }
cranelift-wasm = { path = "../../cranelift/cranelift-wasm", features = ["enable-serde"] }

=======
cranelift-codegen = { version = "0.44.0", features = ["enable-serde"] }
cranelift-entity = { version = "0.44.0", features = ["enable-serde"] }
cranelift-wasm = { version = "0.44.0", features = ["enable-serde"] }
>>>>>>> 872f6aa03dac57539863a92e9f1f6818366e8a4f
wasmtime-jit = { path = "../wasmtime-jit" }
wasmtime-runtime = { path = "../wasmtime-runtime" }
wasmtime-environ = { path = "../wasmtime-environ" }
wabt = "0.9.2"
target-lexicon = "0.8.1"
failure = { version = "0.1.3", default-features = false }
failure_derive = { version = "0.1.3", default-features = false }

[badges]
maintenance = { status = "experimental" }
travis-ci = { repository = "CraneStation/wasmtime" }

[features]
lightbeam = []
