[package]
name = "wasmtime-jit"
version = "0.2.0"
authors = ["The Wasmtime Project Developers"]
description = "JIT-style execution for WebAsssembly code in Cranelift"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/CraneStation/wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
edition = "2018"

[dependencies]
<<<<<<< HEAD
# cranelift-codegen = { version = "0.36.0", features = ["enable-serde"] }
# cranelift-entity = { version = "0.36.0", features = ["enable-serde"] }
# cranelift-wasm = { version = "0.36.0", features = ["enable-serde"] }

cranelift-codegen = { path = "../../cranelift/cranelift-codegen", features = ["enable-serde"] }
cranelift-entity = { path = "../../cranelift/cranelift-entity", features = ["enable-serde"] }
cranelift-wasm = { path = "../../cranelift/cranelift-wasm", features = ["enable-serde"] }

# cranelift-frontend = "0.36.0"
cranelift-frontend = { path = "../../cranelift/cranelift-frontend" }

=======
cranelift-codegen = { version = "0.44.0", features = ["enable-serde"] }
cranelift-entity = { version = "0.44.0", features = ["enable-serde"] }
cranelift-wasm = { version = "0.44.0", features = ["enable-serde"] }
cranelift-frontend = "0.44.0"
>>>>>>> 872f6aa03dac57539863a92e9f1f6818366e8a4f
wasmtime-environ = { path = "../wasmtime-environ", default-features = false }
wasmtime-runtime = { path = "../wasmtime-runtime", default-features = false }
wasmtime-debug = { path = "../wasmtime-debug", default-features = false }
region = "2.0.0"
failure = { version = "0.1.3", default-features = false }
failure_derive = { version = "0.1.3", default-features = false }
<<<<<<< HEAD
target-lexicon = { version = "0.4.0", default-features = false }
hashbrown = { version = "0.1.8", optional = true }
# wasmparser = "0.34.0"
wasmparser = { path = "../../wasmparser.rs"} # default-features = false

=======
target-lexicon = { version = "0.8.1", default-features = false }
hashbrown = { version = "0.6.0", optional = true }
wasmparser = { version = "0.39.1", default-features = false }
>>>>>>> 872f6aa03dac57539863a92e9f1f6818366e8a4f

[features]
default = ["std"]
std = ["cranelift-codegen/std", "cranelift-wasm/std", "wasmtime-environ/std", "wasmtime-debug/std", "wasmparser/std"]
core = ["hashbrown/nightly", "cranelift-codegen/core", "cranelift-wasm/core", "wasmtime-environ/core", "wasmtime-debug/core", "wasmparser/core"]
lightbeam = ["wasmtime-environ/lightbeam"]

[badges]
maintenance = { status = "experimental" }
travis-ci = { repository = "CraneStation/wasmtime" }
